### ISSUE TITLE
scATAC datasets not downloading

### ISSUE THREAD

**Issue by tessadgreen** [sanderlab/scPerturb#1]
click to download doesn't do anything

using the curl script 
curl -X GET 'https://scperturb.org/api/datasets/PierceGreenleaf2021/download/?dataset_index=K562&file_type=mtx' -o ./PierceGreenleaf2021_K562.zip

I get a 43 byte file which Archive utility and unzip both aren't able to open

`Archive:  PierceGreenleaf2021_K562.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
Archive:  PierceGreenleaf2021_K562.ZIP
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.`

**Comment by cannin** [comment]
@joemin @tessadgreen opening the link in a browser gives the message: 

"detail": "That dataset can not be found."

as JSON.
