### ISSUE TITLE
Docstring is incorrect: says edist parameter sample_correct is default True

### ISSUE THREAD

**Issue by deto** [sanderlab/scPerturb#10]
Docstring is incorrect: says edist parameter sample_correct is default True

https://github.com/sanderlab/scPerturb/blob/28b98a70c1c422e22b69a160ec2b34f7947a6c75/package/src/scperturb/edistance.py#L79C9-L79C9

**Comment by stefanpeidli** [comment]
Thanks for the comment! 
Fixed with version 0.0.6 (you can upgrade with `pip install --upgrade scperturb`). Now the sample_correct is True per default as specified in the docstring.
