### ISSUE TITLE
Missing Data in AissaBenevolenskaya2021 Dataset

### ISSUE THREAD

**Issue by lynn-1998** [sanderlab/scPerturb#11]
Hello,

Thanks for the remarkable scperturb database that you have developed. It has been an invaluable resource for my research. However, I have encountered an issue while attempting to download and utilize the `AissaBenevolenskaya2021` dataset. It seems that only processed data for a single SubSerie is available, while a significant amount of data is missing. I have noticed that other users have also raised similar issues.  #5 

I kindly request your assistance in addressing this matter. Could you please make the processed and complete data publicly available, or provide an estimated timeline for its release? Many users are eagerly awaiting access to this missing data. Your prompt response would be greatly appreciated.

Thank youagain for your efforts in creating this valuable resource.

**Comment by stefanpeidli** [comment]
Hi,

Thanks for raising this issue.
I've corrected the processing script and an updated version of that dataset will be uploaded with the next iteration of scperturb. That should happen within the next few weeks. 
Let me know if you need it more urgently.
