### ISSUE TITLE
TypeError: edist() got an unexpected keyword argument 'control'

### ISSUE THREAD

**Issue by mksingh2104** [sanderlab/scPerturb#18]
For: estats = edist(adata, obs_key='drug', obsm_key='X_pca', dist='sqeuclidean', control='control')

Scanpy version: 1.9.8
Traceback (most recent call last):
  File "/home/centos/perturb_data/processed/e-dist/edist.py", line 48, in <module>
    estats = edist(adata, obs_key='drug', obsm_key='X_pca', dist='sqeuclidean', control='control')
TypeError: edist() got an unexpected keyword argument 'control'

**Comment by stefanpeidli** [comment]
The `edist` function computes pairwise edistances between all groups defined by `obs_key='drug'`, so it does not take a control argument.
You can use this instead:
`estats = edist_to_control(adata, obs_key='drug', control='control', obsm_key='X_pca', dist='sqeuclidean')`

Going forward I should probably rename the functions and give a useful warning when providing the control keyword there.
