### ISSUE TITLE
https://www.scperturb.org/datasets throws "Couldn't fetch datasets."

### ISSUE THREAD

**Issue by kaiu85** [sanderlab/scPerturb#2]
Thanks so much for creating this great resource.

I was able to download some scRNAseq data last week, but right now the page https://www.scperturb.org/datasets does not list any datasets and throws the following error:
"Couldn't fetch datasets."

**Comment by cannin** [comment]
@kaiu85 Thanks we are aware of the issue. We've created a secondary download location. You can get the RNA-seq datasets at https://zenodo.org/record/7041849 and ATAC-seq at https://zenodo.org/record/7058382

**Comment by robinfallegger** [comment]
I have the same issue. Do you maybe have the metadata table as well ? Difficult to tell from Zenodo what kind of experiments the files are

**Comment by cannin** [comment]
@demian1 Does Supplementary Table 1 help? 

- Paper Link: https://www.biorxiv.org/content/10.1101/2022.08.20.504663v1.supplementary-material
- Direct Table Link: https://www.biorxiv.org/content/biorxiv/early/2022/08/22/2022.08.20.504663/DC1/embed/media-1.xlsx?download=true

**Comment by cannin** [comment]
Closing for now; re-open if necessary.
