### ISSUE TITLE
Datasets deleted & Number of Cells missing

### ISSUE THREAD

**Issue by ArturDev42** [sanderlab/scPerturb#20]
Hello, I checked [scperturb.org](http://projects.sanderlab.org/scperturb/datavzrd/scPerturb_vzrd_v1/dataset_info/index_1.html) on the 03.03. and found 58 datasets. Today, I see that datasets have been deleted and I can only see 45 datasets. The column **Number of Cells** is also missing. Is this expected or is it maybe a bug? I can also provide the downloaded excel file from 03.03. Thanks!

**Comment by tessadgreen** [comment]
Hi @ArturDev42, I think most likely this is an issue with the website using an old version of the table. We will update that when we're able to, but in the meantime you can access all of the datasets via the current version of our Zenodo repositories. The website points statically to version 1.0 of both RNA and protein, but we're currently at [version 1.3](https://zenodo.org/records/10044268) of the RNA datasets. If you follow the links on scperturb.org and then click on the "newer version available" link on the top of the Zenodo repository to the newest version, that should also get you there.

**Comment by tessadgreen** [comment]
closing here, created new issue to track website update
