### ISSUE TITLE
I wonder if there is any look-up table of columns names explanation of each dataset provided?

### ISSUE THREAD

**Issue by Yonggie** [sanderlab/scPerturb#21]
For example I downloaded 5 random datasets and checked their ``adata.var.columns.value`` and ``adata.obs.columns.value``
![图片](https://github.com/sanderlab/scPerturb/assets/31330044/ec2e9950-4653-4b13-a8ae-94f201cf01e9)

![图片](https://github.com/sanderlab/scPerturb/assets/31330044/8c02d742-388e-4e4d-b88f-5b47100ea939)

Perhaps to understand the names of all requires reading the preprocess codes? 
I wonder if there's a lookup table provided so that we can get to understand these quicker?

**Comment by stefanpeidli** [comment]
Good question! There is a lookup table for the standard annotations in [Supplemental Table 2 of the paper](https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-023-02144-y/MediaObjects/41592_2023_2144_MOESM4_ESM.xlsx). 

However, many annotations were in the original metadata provided by the authors of the respective dataset and therefore not explained in this table. Examples are "hto", which is short for hashtag oligo; short sequences that are used for sample barcoding in scRNA-seq. In these cases it makes sense to look into the original paper (or just write me an email, maybe I can describe some of these at the top of my head directly).

**Comment by Yonggie** [comment]
Oh wow, I've seen this excel, but I forgot to check the sub-tables in the left bottom! THX for the reminder!

**Comment by stefanpeidli** [comment]
Glad I could help!
