### ISSUE TITLE
Pre-Processing File for Norman et al. 

### ISSUE THREAD

**Issue by Hanxi-002** [sanderlab/scPerturb#24]
Hi, 
I wasn't able to find the pre-processing code for Norman et al (2019) in the repo. Would you mind pointing me to the file please?

Thank you so much!

**Comment by tessadgreen** [comment]
it's in one of Judy's notebooks [here](https://github.com/sanderlab/scPerturb/blob/master/dataset_processing/notebooks/data_access_and_preprocessing_JS.ipynb)
