### ISSUE TITLE
Error in .var for SrivatsanTrapnell2020_sciplex3.h5ad

### ISSUE THREAD

**Issue by nrosed** [sanderlab/scPerturb#27]
There seems to be an off-by-one error in the var matrix of the AnnData object.

I run the following code:
`in_file = f"{data_path}/SrivatsanTrapnell2020_sciplex3.h5ad"`
`adata = sc.read_h5ad(in_file)`

Then inspect the var dataframe

`adata.var`

And get the following result:
![Screenshot 2024-08-20 at 12 34 57 PM](https://github.com/user-attachments/assets/837a4e2d-bd96-4f65-9129-418acd81d7bf)

It seems like the header is added as the first content row. The number of rows in adata.X also matches the rows in adata.var, which leads me to believe that the header row is also included in adata.X.

![Screenshot 2024-08-20 at 12 34 22 PM](https://github.com/user-attachments/assets/405a3473-b787-4cf4-adf4-73b705d2be6e)

versions of packages:
`scanpy==1.8.2 anndata==0.8.0 umap==0.5.2 numpy==1.23.5 scipy==1.8.1 pandas==1.5.3 `

**Comment by tessadgreen** [comment]
Thanks for reporting this! 

prev issue: https://github.com/sanderlab/scPerturb/issues/7 

Code is now fixed, we are in the process of updating the files on Zenodo/Figshare to the new version
