### ISSUE TITLE
Missing source code for data processing

### ISSUE THREAD

**Issue by ececillie** [sanderlab/scPerturb#3]
Hi, 

It seems the website is pretty unstable in terms of data hosting (datasets often not displayed or empty ZIP files downloaded). But I noticed you have the data preprocessing source code available on this GitHub repository and all the raw datasets are publicly available. So it should be possible to replicate the preprocessing, which is what I was trying to attempt. But it looks like the "dataset_preprocessing" folder has some missing scripts, such as "utils.py" and "mygene.py". So the existing scripts are currently not replicable due to the missing imports. 
Would you mind uploading these missing scripts please?
Thanks

**Comment by tessadgreen** [comment]
mygene is a package available [here](https://pypi.org/project/mygene/), and utils.py is in the [main folder](https://github.com/sanderlab/scPerturb/blob/master/utils.py)

While we work on getting the website up and running again, we've created a secondary download location. You can get the RNA-seq datasets at https://zenodo.org/record/7041849  and ATAC-seq at https://zenodo.org/record/7058382

**Comment by ececillie** [comment]
Thank you for your response; this was very helpful!
