### ISSUE TITLE
suggestion: provide a function for calculating E-distance

### ISSUE THREAD

**Issue by AstreChen** [sanderlab/scPerturb#4]
It will be convenient to provide a function for calculating E-distance, which can act as a step of quality control

**Comment by stefanpeidli** [comment]
Great suggestion, I'll work on it!

**Comment by stefanpeidli** [comment]
Just created a new python package and pushed to PyPI.
Feel free to try it out! Simply install using:

```
pip install scperturb
```

Check out [this notebook](https://github.com/sanderlab/scPerturb/blob/master/package/notebooks/e-distance.ipynb) for a tutorial.
