### ISSUE TITLE
Wrong 'perturbation' tag of data

### ISSUE THREAD

**Issue by siduanmiao** [sanderlab/scPerturb#6]
Hello,
In the data of your `GSM2396860_K562_TFs__High_MOI` data of DixitRegev2016.h5ad, you give the cell barocde which is not included in cbc_gbc_dict a tag "control" in the adata.obs['perturbation'], but the true control groups is cells knocked by 'INTERGENIC216151','INTERGENIC1144056','INTERGENIC393453' and 'INTERGENIC1216445'. This will influence the downsteam work if the 'control' tag is given to these cells without sgRNA knocking. 
May the 'None' tag is better than 'control'? This is such an excellent works.

**Comment by tessadgreen** [comment]
Resolved, updated scripts now on scPerturb and updated data will be included in the forthcoming Zenodo version 1.4
